name: project_2_saad_alharbi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.2
  flutter_svg: ^0.22.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/




  fonts:
    - family: Ribeye
      fonts:
        - asset: fonts\Ribeye-Regular.ttf
